export const theme = {
  as: {
    h: 'header',
    m: 'main',
    f: 'footer',
    s: 'section',
    d: 'div',
  },
  display: {
    none: 'none',
    b: 'block',
    f: 'flex',
    g: 'grid',
    ib: 'inline-block',
    if: 'inline-flex',
    ig: 'inline-grid',
  },
  position: {
    l: 'left',
    c: 'center',
    r: 'right',
    a: 'auto',
  },
  colors: {
    black: '#000',
    white: '#fff',
    text: '#2a2a2a',
    bgSection: '#d0d0d0',
    bgCard: '#eee',
    tableLine: '#ddd',
    bgWhite: '#fff',
    primary: '#07c',
    secondary: '#05a', 
    accent: '#609',
    accentLight: '#ae66d1',
    muted: '#f6f6f6',
    green: '#008000',
    red: '#f00',
  },
  space: [0, 2, 4, 8, 16, 32, 64, 128, 256, 320, 480, 512, 768, 1024],
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'system-ui, sans-serif',
    monospace: 'Menlo, monospace',
  },
  fontSizes: {
    xs: '12px',
    s: '14px',
    m: '16px',
    l: '24px',
    xl: '32px',
    xxl: '64px',
    xxxl: '128px',
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    normal: '4px',
    big: '12px',
    round: '50%',
  },
  shadows: {
    card: '1px 1px 4px 0px rgba(102, 102, 130, 1)',
  },
};